### ISSUE TITLE
cannot deleted user from voucher.html

### ISSUE THREAD

**Issue by niammuddin** [mangospot-net/MangoSpot#1]
tidak bisa hapus user/voucher dari halaman voucher.html, hanya bisa dari halaman users.html

**Comment by mangospot-net** [comment]
> tidak bisa hapus user/voucher dari halaman voucher.html, hanya bisa dari halaman users.html

Silahkan di coba versi terbarunya, semoga bisa membantu.

**Comment by niammuddin** [comment]
versi terbaru saat import database banyak yang error om

**Comment by niammuddin** [comment]
saat import ini:
CREATE VIEW expiredgroup AS
  SELECT 
    a.identity,
    a.users,
    a.username,
    c.groupname AS profile,
    a.attribute,
    a.value,
    d.price,
    d.discount,
    CASE 
      WHEN d.discount IS NULL THEN d.price 
      ELSE d.price - d.discount 
    END AS total,
    date_format(min(b.acctstarttime),'%Y-%m-%d %H:%i') AS time,
    date_format(from_unixtime(unix_timestamp(b.acctstarttime) + a.value),'%Y-%m-%d %H:%i') AS expired 
  FROM expiredcheck a JOIN radacct b ON a.username = b.username 
  LEFT JOIN radusergroup c ON a.username = c.username AND a.identity = c.identity
  LEFT JOIN radprice d ON c.groupname = d.groupname AND a.identity = d.identity 
  WHERE a.attribute = 'Access-Period' AND unix_timestamp(b.acctstarttime) + a.value < unix_timestamp() 
  GROUP BY a.identity,a.users,a.username,c.groupname,a.attribute,a.value,d.price,d.discount 
UNION 
  SELECT 
    a.identity,
    a.users,
    a.username,
    c.groupname AS profile,
    a.attribute,
    a.value,
    d.price,
    d.discount,
    CASE 
      WHEN d.discount IS NULL THEN d.price 
      ELSE d.price - d.discount 
    END AS total,
    date_format(min(b.acctstarttime),'%Y-%m-%d %H:%i') AS time,
    formatbytes(sum(b.acctinputoctets) + sum(b.acctoutputoctets)) AS expired 
  FROM expiredcheck a JOIN radacct b ON a.username = b.username 
  LEFT JOIN radusergroup c ON a.username = c.username AND a.identity = c.identity 
  LEFT JOIN radprice d ON c.groupname = d.groupname AND a.identity = d.identity 
  WHERE a.attribute = 'Max-Data' 
  GROUP BY a.identity,a.users,a.username,c.groupname,a.attribute,a.value,d.price,d.discount 
  HAVING a.value - (sum(b.acctinputoctets) + sum(b.acctoutputoctets)) <= 0;

CREATE VIEW expired AS
  SELECT 
    a.identity, 
    a.users, 
    a.username, 
    a.profile, 
    a.price, 
    a.discount, 
    a.total, 
    a.time, 
    concat(formatbytes(sum(b.acctinputoctets)), ' / ', formatbytes(sum(b.acctoutputoctets))) as 'usage',
    sum(b.acctinputoctets) AS upload,
    sum(b.acctoutputoctets) AS download,
    (sum(b.acctinputoctets) + sum(b.acctoutputoctets)) AS quota
  FROM expiredgroup a LEFT JOIN radacct b on a.username = b.username
  WHERE a.expired IS NOT NULL
  GROUP BY a.identity, a.users, a.username, a.profile, a.price, a.discount, a.total, a.time;

**Comment by mangospot-net** [comment]
Coba function formatbytes di input manual dulu, baru import view.

**Comment by niammuddin** [comment]
sudah saya input manual semua, bagian yg error 2 itu. lainnya sukses

**Comment by mangospot-net** [comment]
CREATE FUNCTION formatbytes(byte BIGINT) RETURNS VARCHAR(200)BEGIN DECLARE bytes VARCHAR(200);	CASE		WHEN (byte >= 1099511627776) THEN SET bytes = CONCAT(FORMAT((byte / 1099511627776), 2), 'TB');		WHEN (byte >= 1073741824) THEN SET bytes = CONCAT(FORMAT((byte / 1073741824), 2), 'GB'); 		WHEN (byte >= 1048576) THEN SET bytes = CONCAT(FORMAT((byte / 1048576), 2), 'MB'); 		WHEN (byte >= 1024) THEN SET bytes = CONCAT(FORMAT((byte / 1024), 2), 'KB'); 		WHEN (byte > 1) THEN SET bytes = CONCAT(FORMAT((byte), 2), 'B');		ELSE SET bytes = byte;	END CASE;	RETURN bytes;END;

Coba di cek, apakah function di atas sudah masuk apa belum?

**Comment by niammuddin** [comment]
saya coba2 lagi bagian ini yg mengalami error:
saya coba hapus "UNION" keterangan sukses impornya, union disini buat apa ya?

UNION 
  SELECT 
    a.identity,
    a.users,
    a.username,
    c.groupname AS profile,
    a.attribute,
    a.value,
    d.price,
    d.discount,
    CASE 
      WHEN d.discount IS NULL THEN d.price 
      ELSE d.price - d.discount 
    END AS total,
    date_format(min(b.acctstarttime),'%Y-%m-%d %H:%i') AS time,
    formatbytes(sum(b.acctinputoctets) + sum(b.acctoutputoctets)) AS expired 
  FROM expiredcheck a JOIN radacct b ON a.username = b.username 
  LEFT JOIN radusergroup c ON a.username = c.username AND a.identity = c.identity 
  LEFT JOIN radprice d ON c.groupname = d.groupname AND a.identity = d.identity 
  WHERE a.attribute = 'Max-Data' 
  GROUP BY a.identity,a.users,a.username,c.groupname,a.attribute,a.value,d.price,d.discount 
  HAVING a.value - (sum(b.acctinputoctets) + sum(b.acctoutputoctets)) <= 0;

**Comment by mangospot-net** [comment]
CREATE VIEW expiredgroup AS
  SELECT 
    a.identity,
    a.users,
    a.username,
    c.groupname AS profile,
    a.attribute,
    a.value,
    d.price,
    d.discount,
    CASE 
      WHEN d.discount IS NULL THEN d.price 
      ELSE d.price - d.discount 
    END AS total,
    date_format(min(b.acctstarttime),'%Y-%m-%d %H:%i') AS time,
    CHAR(date_format(from_unixtime(unix_timestamp(b.acctstarttime) + a.value),'%Y-%m-%d %H:%i')) AS expired 
  FROM expiredcheck a JOIN radacct b ON a.username = b.username 
  LEFT JOIN radusergroup c ON a.username = c.username AND a.identity = c.identity
  LEFT JOIN radprice d ON c.groupname = d.groupname AND a.identity = d.identity 
  WHERE a.attribute = 'Access-Period' AND unix_timestamp(b.acctstarttime) + a.value < unix_timestamp() 
  GROUP BY a.identity,a.users,a.username,c.groupname,a.attribute,a.value,d.price,d.discount 
UNION 
  SELECT 
    a.identity,
    a.users,
    a.username,
    c.groupname AS profile,
    a.attribute,
    a.value,
    d.price,
    d.discount,
    CASE 
      WHEN d.discount IS NULL THEN d.price 
      ELSE d.price - d.discount 
    END AS total,
    date_format(min(b.acctstarttime),'%Y-%m-%d %H:%i') AS time,
    CHAR(formatbytes(sum(b.acctinputoctets) + sum(b.acctoutputoctets))) AS expired 
  FROM expiredcheck a JOIN radacct b ON a.username = b.username 
  LEFT JOIN radusergroup c ON a.username = c.username AND a.identity = c.identity 
  LEFT JOIN radprice d ON c.groupname = d.groupname AND a.identity = d.identity 
  WHERE a.attribute = 'Max-Data' 
  GROUP BY a.identity,a.users,a.username,c.groupname,a.attribute,a.value,d.price,d.discount 
  HAVING a.value - (sum(b.acctinputoctets) + sum(b.acctoutputoctets)) <= 0;

Coba expiredgroup view nya ganti ini om.

**Comment by niammuddin** [comment]
sip sukses om, makasih

**Comment by mangospot-net** [comment]
Ok, sama om.

**Comment by niammuddin** [comment]
setelah sukses dan coba2 fiturnya, ada beberapa kendala nih, 

1. di halaman expired.html tidak tampil user yg expired hanya "No matching records found + Showing 1 to 1 of 1 entries" ketika ada 1 user yg expired
2. payment.html juga tidak menampilkan data
3. profile.html tidak bisa diedit.

**Comment by mangospot-net** [comment]
Sudah coba di clear cache belum om?

**Comment by niammuddin** [comment]
sudah, pakai browser lain juga sama

**Comment by mangospot-net** [comment]
Sudah coba di buka file js nya trs di reload?
buka domain/dist/js/expired.js -> reload

Pada table view expired ada data nya gk om?

**Comment by niammuddin** [comment]
ini om js dan table view
<img width="794" alt="Screen Shot 2020-01-24 at 09 11 39" src="https://user-images.githubusercontent.com/6014789/73039723-c254cb00-3e89-11ea-8ab7-208cdad26ecf.png">
<img width="1130" alt="Screen Shot 2020-01-24 at 09 12 59" src="https://user-images.githubusercontent.com/6014789/73039725-c2ed6180-3e89-11ea-8630-e11f9dd6be6e.png">

**Comment by mangospot-net** [comment]
Kemungkinan itu cookie nya om.
Sudah coba di browser smartphone?

**Comment by niammuddin** [comment]
sudah om, sudah saya coba install di device lain scriptnya juga problemnya sama

**Comment by wirebox4556** [comment]
nggk bisa export voucher versi mobile om
