### ISSUE TITLE
MYSQL SYNTAX ISSUE IN 1-schema-mysql.sql

### ISSUE THREAD

**Issue by vikrum669** [mangospot-net/MangoSpot#5]
There seems to be an issue in 1-schema-mysql.sql at line 518. 

![Screenshot 2020-03-04 21:37:35](https://user-images.githubusercontent.com/42598888/75897356-88032400-5e60-11ea-94bf-d242c7183691.png)

**Comment by metallicats** [comment]
I'm also getting this error. Did anyone fix this yet?

**Comment by mangospot-net** [comment]
You can replace 'row_number (order by a.groupname) AS id' to a.id
